backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: public/
collections: 
  - name: "review"
    label: "Review"
    folder: "_reviews"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields: 
      - {label: "name", name: "Name", widget: "string", required: true}
      - {label: "date", name: "Date", widget: "datetime", required: true}
      - {label: "body", name: "Body", widget: "markdown"}