backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: public/
public_folder: "public"
collections: 
  - name: "review"
    label: "Review"
    folder: "_reviews"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{name}}"
    fields: 
      - {label: "Name", name: "name", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "date", date_format: "DD-MM-YYYY", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "gallery"
    label: "Gallery"
    media_folder: /carouselImages
    public_folder: "/carouselImages"
    slug: "{{year}}-{{month}}-{{day}}-{{name}}"
    fields: 
      - {label: "Name", name: "name", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "date", date_format: "DD-MM-YYYY", required: true}
      - {label: "Carousel Image", name: "image", widget: "image", required: true}