backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: public/
public_folder: "public"
collections: 
  - name: "review"
    label: "Review"
    folder: "_reviews"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{name}}"
    fields: 
      - {label: "Name", name: "name", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "date", date_format: "DD-MM-YYYY", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "carousel"
    label: "Carousel"
    widget: object
    media_folder: /carouselImages
    public_folder: "/carouselImages"
    summary: '{{fields.header}}'
    fields: 
      - { label: Header, name: header, widget: string, default: 'Image Galelry'}
      - {label: Template, name: template, widget: string, default: '/pages/gallery/index.js'}
      - label: Images
        name: images
        widget: list
        field: { label: Image, name: image, widget: image }